spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/FinalBackEnd
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true

  rabbitmq:
    username: guest
    password: guest
    host: rabbit-mq

server:
  port: 8081
  
queue:
  movie:
    name: movieQueue

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
